# Generated by Django 5.2.14 on 2026-06-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveWebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('speaker', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='webinars/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
