# Generated by Django 5.2.14 on 2026-06-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_livewebinar'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedin_url', models.URLField()),
                ('webinar_title', models.CharField(max_length=255)),
                ('registration_status', models.CharField(choices=[('Registered', 'Registered'), ('Attended', 'Attended'), ('Cancelled', 'Cancelled')], default='Registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('email', 'webinar_title')},
            },
        ),
    ]
