# Generated by Django 5.2.14 on 2026-06-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_webinarregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='livewebinar',
            name='title',
            field=models.CharField(default='Future of Oracle Cloud Infrastructure', max_length=255),
        ),
    ]
