# Generated by Django 5.2.14 on 2026-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_videoshowcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslider',
            name='image',
            field=models.ImageField(help_text='Recommended image size: 1672 × 941 pixels', upload_to='hero_slider/'),
        ),
    ]
