# Generated by Django 5.2.14 on 2026-06-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_heroslider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livewebinar',
            name='speaker',
            field=models.CharField(help_text='For multiple speakers, separate names with a comma (,). Example: Dhananjay G, KARINA PAWAR', max_length=255),
        ),
    ]
