# Generated by Django 5.2.14 on 2026-06-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_livewebinar_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCloudStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team_cloudstand/')),
                ('is_hero_image', models.BooleanField(default=False, help_text='Check this option to display this image in the Hero Section.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
