# Generated by Django 5.2.14 on 2026-06-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_teamcloudstand'),
    ]

    operations = [
        migrations.AddField(
            model_name='openrole',
            name='additional_advantage',
            field=models.TextField(blank=True, help_text="Use ',' (comma) to separate each additional advantage."),
        ),
        migrations.AddField(
            model_name='openrole',
            name='benefits',
            field=models.TextField(blank=True, help_text="Use ',' (comma) to separate each benefit."),
        ),
        migrations.AddField(
            model_name='openrole',
            name='key_responsibilities',
            field=models.TextField(blank=True, help_text="Use ',' (comma) to separate each responsibility."),
        ),
        migrations.AddField(
            model_name='openrole',
            name='preferred',
            field=models.TextField(blank=True, help_text="Use ',' (comma) to separate each preferred skill."),
        ),
        migrations.AddField(
            model_name='openrole',
            name='requirements',
            field=models.TextField(blank=True, help_text="Use ',' (comma) to separate each requirement."),
        ),
    ]
